package com.tejas.tejascalculator;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.WindowManager;

public class SplashActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getSupportActionBar().hide();
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);

        setContentView(R.layout.activity_splash);

        Thread thread=new Thread(){//thread use where we have to do parallel multiple task at one time...

            public void run(){//this method is inbuilt in thread class in java

                //Now we use exception handling here cos may be delay generate some errors
                //we write our code in try(this is the code that we think might generate some errors.
                //Use of exceptional handling is that in case of error our code(written in try )app didn't crash and instead show some
                // exception like file not found or any arithmetic exception(written in catch block) and finally block shows alternative
                // solution code
                try {
                    sleep(4000);// sleep method is use for delay and 1000 milli sec=1s
                }
                catch (Exception e){
                    //her you can write exception name if you knbow which type of exception generate from try block
                    //in case you don't know exception name we write
                    e.printStackTrace();//printStackTrace is the mother of all exception that show any
                    // exception that generated by the try block cod error.
                }

                finally{
                    //in finally we use intent(Intent in java use for going from one activity to another.)
                    Intent myIntent = new Intent(SplashActivity.this, MainActivity.class);
                    startActivity(myIntent);

                }

            }
        };thread.start();//this strat the above created thread for showing splash screen


    }
}